const express = require("express");
const router = require("./router");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();
const PORT = process.env.PORT || 5000;
app.use(bodyParser.json());
app.use(cors());
router(app);
app.listen(PORT, () => console.log(`Express server started on ${PORT}`));
